export const ADD_CAMPUS = 'ADD_CAMPUS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_CAMPUSES = 'GET_CAMPUSES';
export const GET_STUDENTS = 'GET_STUDENTS'
export const REMOVE_CAMPUS = 'REMOVE_CAMPUS';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
