export const ADD_CAMPUS = 'ADD_CAMPUS';
export const ADD_CAMPUS_TO_STUDENT = 'ADD_CAMPUS_TO_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_CAMPUSES = 'GET_CAMPUSES';
export const REMOVE_CAMPUS = 'REMOVE_CAMPUS';
export const REMOVE_CAMPUS_FROM_STUDENT = 'REMOVE_CAMPUS_FROM_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';
export const UPDATE_CAMPUS = 'UPDATE_CAMPUS';
